### ISSUE TITLE
ShapekeyMaster just doesn't work

### ISSUE THREAD

**Issue by HenBor2** [krypto5863/COM3D2.ShapekeyMaster#1]
I installed everything according to the instructions, both plugins are installed and running (according to the console), however, nothing happens when I try to change the values
https://imgur.com/oYmiy3w
I try: delete SA, run all vers of plugin, port some keys from SA, Don't port keys from SA
Game ver: 1,490, BepInEx: 5.3.0.0

**Comment by krypto5863** [comment]
Your BepinEx and game version are very old. SM was built against BepinEx 5.11 and game ver 1.54

Please update your game and BepinEx(Or CMI if you use it) to the latest and things should work as expected.

**Comment by HenBor2** [comment]
thank you!

**Comment by HenBor2** [comment]
But please, add this info to readme

**Comment by krypto5863** [comment]
Will do.
