### ISSUE TITLE
Disable ShapeKey settings but still not unload ShapeKey

### ISSUE THREAD

**Issue by InoryS** [krypto5863/COM3D2.ShapekeyMaster#3]
First of all, thank you so much for making this plugin!
but I have some problems.

Sometimes, I want to temporarily disable my shapekey control in ShapekeyMaster so that other plugins can control it.
But when I disable that ShapeKey in ShapekeyMaster, other plugins still can't control it.
When I use ShapeAnimator, after disabling ShapeKey, other plugins can control can control that key.

Finally, I think it would be better for the normal mode to also show the ShapeKey name.

**Comment by krypto5863** [comment]
Can't do anything about ShapekeyMaster taking full control of keys, even disabled. Users prefer that key disabling sets the key to 0, so I'd be going against their wishes. It's just a lose-lose situation. I'll consider what can be done.

Sure that last one is do-able.
